services:
  db:
    image: mariadb
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo-local
      MYSQL_USER: my-todo
      MYSQL_PASSWORD: todo1!
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
